name       : swayidle
version    : 1.8.0
release    : 4
source     :
    - https://github.com/swaywm/swayidle/archive/refs/tags/1.8.0.tar.gz : 0fba74c520a2bd64acd00bc3bce7bc8c7b84a2609c0f66329d72dfb33cca03d7
license    : MIT
homepage   : https://github.com/swaywm/swayidle
component  : desktop
summary    : Sway's idle management daemon. It is compatible with any Wayland compositor which implements the KDE idle protocol.
description: |
    Sway's idle management daemon. It is compatible with any Wayland compositor which implements the KDE idle protocol.
builddeps  :
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
