name       : swayidle
version    : 1.7.1
release    : 3
source     :
    - https://github.com/swaywm/swayidle/archive/refs/tags/1.7.1.tar.gz : 6aa07093be553473726e1ef601dbc5e57a3ea2ac864ef2d7afce1f971ea760a6
license    : MIT
homepage   : https://github.com/swaywm/swayidle
component  : desktop
summary    : Sway's idle management daemon. It is compatible with any Wayland compositor which implements the KDE idle protocol.
description: |
    Sway's idle management daemon. It is compatible with any Wayland compositor which implements the KDE idle protocol.
builddeps  :
    - pkgconfig(scdoc)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
